CREATE DATABASE OptusMusical

USE OptusMusical

CREATE TABLE Musico(
idMusico SMALLINT PRIMARY KEY IDENTITY,
Nome VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Estilo(
idEstilo TINYINT PRIMARY KEY IDENTITY,
EstiloMusical VARCHAR(30) NOT NULL UNIQUE
)
GO

CREATE TABLE Album(
idAlbum SMALLINT PRIMARY KEY IDENTITY,
Titulo VARCHAR(30),
DataLancamento DATETIME,
Localizacao VARCHAR(200),
Minutagem VARCHAR(6),
Visivel BINARY,
idMusico SMALLINT FOREIGN KEY REFERENCES Musico(idMusico),
idEstilo TINYINT FOREIGN KEY REFERENCES Estilo(idEstilo)
)
GO