CREATE DATABASE ClinicaVeterinaria

USE ClinicaVeterinaria

CREATE TABLE Clinica(
idClinica SMALLINT PRIMARY KEY IDENTITY,
Endereco VARCHAR(200) NOT NULL UNIQUE,
)

CREATE TABLE TipoPet(
idTipoPet TINYINT PRIMARY KEY IDENTITY,
Tipo VARCHAR(30) NOT NULL UNIQUE,
)

CREATE TABLE Raca(
idRaca TINYINT PRIMARY KEY IDENTITY,
Nome VARCHAR(50) NOT NULL UNIQUE,
)

CREATE TABLE Dono(
idDono SMALLINT PRIMARY KEY IDENTITY,
Nome VARCHAR(40)
)

CREATE TABLE Pet(
idPet SMALLINT PRIMARY KEY IDENTITY,
Apelido VARCHAR(40) NOT NULL,
DataNascimento VARCHAR(8),
idTipoPet TINYINT FOREIGN REFRENCES TipoPet(idTipoPet),
idRaca TINYINT FOREIGN REFERENCES Raca(idRaca),
idDono SMALLINT FOREIGN KEY REFERENCES Dono(idDono)
)

CREATE TABLE Funcionario(
idFuncionario SMALLINT PRIMARY KEY IDENTITY,
Nome VARCHAR(40) NOT NULL
)

CREATE TABLE Atendimento(
idAtendimento SMALLINT PRIMARY KEY IDENTITY,
idFuncionario SMALLINT FOREIGN KEY REFERENCES Funcionario(idFuncionario),
idPet SMALLINT FOREIGN KEY REFERENCES Pet(idPet),
DataConsulta DataTime,
Descricao VARCHAR(200)
)

