CREATE DATABASE WishList_Senai

USE WishList_Senai

CREATE TABLE Usuarios(
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Senha VARCHAR(16) NOT NULL CHECK (LEN(Senha) >= 8)
)

CREATE TABLE ListaDesejos(
	idDesejo SMALLINT PRIMARY KEY IDENTITY,
	idUsuario SMALLINT FOREIGN KEY REFERENCES Usuarios(idUsuario),
	Descricao VARCHAR(250) NOT NULL,
	DataCriacao DATETIME
)
